language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository ppa:deadsnakes/ppa -y # Newer Python for Meson
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install python3.6-venv libwebkit2gtk-4.0 libsoup2.4 pkg-config

script:
  # Autoconf
  - wget http://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz
  - tar xf autoconf*
  - cd autoconf-*/
  - sh configure --prefix /usr
  - make -j$(nproc)
  - sudo make install
  - autoconf --version
  - cd -
  # Automake
  - wget http://ftp.gnu.org/gnu/automake/automake-1.16.1.tar.gz
  - tar xf automake*
  - cd automake-*/
  - sh configure --prefix /usr
  - make -j$(nproc)
  - sudo make install
  - automake --version
  - cd -
  # Libtool
  - wget http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.gz
  - tar xf libtool*
  - cd libtool-*/
  - sh configure --prefix /usr
  - make -j$(nproc)
  - sudo make install 
  - libtool --version
  - cd -
  # https://github.com/GNOME/gjs
  - git clone https://github.com/GNOME/gjs
  - cd gjs
  - ./autogen.sh
  - make
  - sudo make install
  - cd ..
  # Install Meson "manually"
  - virtualenv -p python3 ./ # Create virtualenv
  - source bin/activate      # Activate the virtualenv
  - pip3 install meson       # Install Meson
  - hash -r                  # Refresh bash paths
  - cd ..
  # Install Ninja "manually"
  - git clone git://github.com/ninja-build/ninja.git
  - cd ninja
  - git checkout release
  - ./configure.py --bootstrap
  - mkdir -p ../bin
  - cp ninja ../bin
  - BINDIR=$(readlink -f ../bin)
  - cd ..
  # foliate
  - meson . build --prefix /usr
  - ninja -C build
  - sudo ninja -C build install
  - cd ..
